'use strict';

module.exports = [ { type: 'put',
    key: 'localhost/daily/intelligencer/components/meta-icons/instances/di@published',
    value: '{"siteName":"Daily Intelligencer","favicon":"//cache.nymag.com/media/di/favicon.ico","icon76":"//cache.nymag.com/media/di/icon.76x76.png","icon120":"//cache.nymag.com/media/di/icon.120x120.png","icon144":"//cache.nymag.com/media/di/icon.144x144.png","icon152":"//cache.nymag.com/media/di/icon.152x152.png","icon180":"//cache.nymag.com/media/di/icon.180x180.png","icon196":"//cache.nymag.com/media/di/icon.196x196.png","iconSVG":"//cache.nymag.com/media/di/icon.svg","maskSVG":"//cache.nymag.com/media/di/mask.svg","maskColor":"#ff5656"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/clay-meta-keywords/instances/di@published',
    value: '{"tags":["index","New York","New York news","culture","business","finance","real estate","parties","Manhattan","Brooklyn","Queens","Bronx","Staten Island","Daily Intelligencer","New York Magazine","NYC"]}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/clay-meta-site/instances/index@published',
    value: '{"twitter":"@intelligencer","facebook":"NewYorkMag","facebookID":120608177953522,"siteName":"Daily Intelligencer","ogType":"Website"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/meta-image/instances/index@published',
    value: '{"default":"//nymag.com/daily/intelligencer/media/sites/di/icon.1500x1500.png"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/clay-meta-description/instances/index@published',
    value: '{"description":"New York Magazine’s coverage of today’s biggest news in politics, tech, and media includes commentary from Jonathan Chait, Frank Rich, Annie Lowery and more."}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/clay-meta-url/instances/index@published',
    value: '{"url":"http://nymag.com/daily/intelligencer/"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/clay-meta-title/instances/index@published',
    value: '{"title":"Daily Intelligencer -- New York News -- New York Magazine","ogTitle":"Daily Intelligencer -- New York News -- New York Magazine","twitterTitle":"Daily Intelligencer -- New York News -- New York Magazine"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/global-nav/instances/social-off@published',
    value: '{"socialButtons":true,"enableLogin":true}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/ad/instances/topLeaderboardMobileHomepage@published',
    value: '{"description":"Top leaderboard on Mobile","name":"/4088/nym.nymag/Daily_Intelligencer_Mobile","label":"TopLeaderboard","viewportMax":480,"sizes":"320x50,320x100,320x101"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/ad/instances/topLeaderboardMobileLandscapeHomepage@published',
    value: '{"description":"Top leaderboard on Mobile Landscape","name":"/4088/nym.nymag/Daily_Intelligencer_Mobile","label":"TopLeaderboard","viewportMin":480,"viewportMax":728,"sizes":"468x60,480x60"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/newsletter-sign-up-button/instances/di@published',
    value: '{"text":"Get the Newsletter","title":"Newsletter","subtitle":"Get Daily Intelligencerʼs Top Stories Delivered Daily","newsletterId":2093417465,"source":"di","emailMessage":"Enter your email","signUpMessage":"Sign Up","successMessage":"Thank you for signing up!","errorMessage":"An error occurred. Please try again.","closeMessage":"Close the newsletter signup modal."}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/follow/instances/twitter@published',
    value: '{"socialNetwork":"twitter","handle":"@intelligencer","buttonText":"Follow Us"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/follow/instances/facebook@published',
    value: '{"socialNetwork":"facebook","handle":"NewYorkMag","buttonText":"Like Us"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/newsletter-sign-up-button/instances/di@published',
    value: '{"text":"Get the Newsletter","title":"Newsletter","subtitle":"Get Daily Intelligencerʼs Top Stories Delivered Daily","newsletterId":2093417465,"source":"di","emailMessage":"Enter your email","signUpMessage":"Sign Up","successMessage":"Thank you for signing up!","errorMessage":"An error occurred. Please try again.","closeMessage":"Close the newsletter signup modal."}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/follow/instances/twitter@published',
    value: '{"socialNetwork":"twitter","handle":"@intelligencer","buttonText":"Follow Us"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/follow/instances/facebook@published',
    value: '{"socialNetwork":"facebook","handle":"NewYorkMag","buttonText":"Like Us"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/search/instances/global@published',
    value: '{"searchtext":"Search"}' },
  { key: 'localhost/daily/intelligencer/components/top-story/instances/2@published',
    type: 'put',
    value: '{"url":""}' },
  { key: 'localhost/daily/intelligencer/components/top-story/instances/1@published',
    type: 'put',
    value: '{"url":""}' },
  { key: 'localhost/daily/intelligencer/components/top-story/instances/0@published',
    type: 'put',
    value: '{"url":""}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/early-often/instances/di@published',
    value: '{"authors":[{"text":"Rembert Browne"},{"text":"Jonathan Chait"},{"text":"Marin Cogan"},{"text":"Ed Kilgore"},{"text":"Eric Levitz"},{"text":"Annie Lowrey"},{"text":"Frank Rich"},{"text":"Gabriel Sherman"},{"text":"Rebecca Traister"}]}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/top-stories/instances/index@published',
    value: '{"title":"Top Stories","topStory0":{"_ref":"localhost/daily/intelligencer/components/top-story/instances/0@published"},"topStory1":{"_ref":"localhost/daily/intelligencer/components/top-story/instances/1@published"},"topStory2":{"_ref":"localhost/daily/intelligencer/components/top-story/instances/2@published"}}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/simple-header/instances/index@published',
    value: '{"position":"bottom","hasStrongSiteName":true,"search":{"_ref":"localhost/daily/intelligencer/components/search/instances/global@published"},"services":[{"_ref":"localhost/daily/intelligencer/components/follow/instances/facebook@published"},{"_ref":"localhost/daily/intelligencer/components/follow/instances/twitter@published"},{"_ref":"localhost/daily/intelligencer/components/newsletter-sign-up-button/instances/di@published"}]}' },
  { key: 'localhost/daily/intelligencer/components/di-header/instances/index@published',
    value: '{"hasDropdown":false,"magazineImageUrl":"http://images.nymag.com/current_issue.jpg","services":[{"_ref":"localhost/daily/intelligencer/components/follow/instances/facebook@published"},{"_ref":"localhost/daily/intelligencer/components/follow/instances/twitter@published"},{"_ref":"localhost/daily/intelligencer/components/newsletter-sign-up-button/instances/di@published"}],"subscribeUrl":"//nymag.com/maglinks/nym-di-01","giftUrl":"//nymag.com/maglinks/nym-di-02","digitalUrl":"//nymag.com/maglinks/nym-di-03","subscribeTrack":"DI Index: Nav: Masthead: Magazine Subscription: Subscribe","giftTrack":"DI Index: Nav: Masthead: Magazine Subscription: Gift","digitalTrack":"DI Index: Nav: Masthead: Magazine Subscription: Digital"}',
    type: 'put' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/ad/instances/outOfPageHomepage@published',
    value: '{"description":"Out of page interstitial","name":"/4088/nym.nymag/Daily_Intelligencer","label":"outOfPage","viewportMin":0,"sizes":null}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/ad/instances/topLeaderboardTabletHomepage@published',
    value: '{"description":"Top leaderboard on Tablet","name":"/4088/nym.nymag/Daily_Intelligencer","label":"TabletLeaderboard","viewportMin":728,"viewportMax":1024,"sizes":"728x90"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/ad/instances/topLeaderboardDesktopHomepage@published',
    value: '{"description":"Top leaderboard on Desktop","name":"/4088/nym.nymag/Daily_Intelligencer","label":"TopLeaderboard","viewportMin":1024,"sizes":"728x90,970x90,1024x90,970x250"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/masthead-editor/instances/7@published',
    value: '{"name":"Rebecca Traister","twitter":"rtraister"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/masthead-editor/instances/6@published',
    value: '{"name":"Annie Lowrey","twitter":"annielowrey"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/masthead-editor/instances/5@published',
    value: '{"name":"Eric Levitz","twitter":"EricLevitz"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/masthead-editor/instances/4@published',
    value: '{"name":"Ed Kilgore","twitter":"ed_kilgore"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/masthead-editor/instances/3@published',
    value: '{"name":"Margaret Hartmann","twitter":"MargHartmann"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/masthead-editor/instances/2@published',
    value: '{"name":"Marin Cogan","twitter":"marincogan"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/masthead-editor/instances/1@published',
    value: '{"name":"Jonathan Chait","twitter":"jonathanchait"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/masthead-editor/instances/0@published',
    value: '{"name":"Rembert Browne","twitter":"rembert"}' },
  { key: 'localhost/daily/intelligencer/components/greatest-hit/instances/2@published',
    type: 'put',
    value: '{"title":"How Crazy Am I to Think I Actually Know Where That Malaysia Airlines Plane Is?","image":"http://pixel.nymag.com/imgs/daily/intelligencer/2015/02/19/magazine/22-malaysia.w1200.h630.jpg","url":"http://nymag.com/daily/intelligencer/2015/02/jeff-wise-mh370-theory.html","plaintextTitle":"How Crazy Am I to Think I Actually Know Where That Malaysia Airlines Plane Is?"}' },
  { key: 'localhost/daily/intelligencer/components/greatest-hit/instances/1@published',
    type: 'put',
    value: '{"title":"Ellen Pao and the Sexism You Can’t Quite Prove","image":"http://pixel.nymag.com/imgs/daily/intelligencer/2015/03/27/27-ellen-pao.o.jpg/a_560x375.w1200.h630.jpg","url":"http://nymag.com/daily/intelligencer/2015/03/ellen-pao-and-the-sexism-you-cant-quite-prove.html","plaintextTitle":"Ellen Pao and the Sexism You Can’t Quite Prove"}' },
  { key: 'localhost/daily/intelligencer/components/greatest-hit/instances/0@published',
    type: 'put',
    value: '{"title":"The Disastrous Clinton Post-Presidency","image":"http://pixel.nymag.com/imgs/daily/intelligencer/2015/04/23/23-bill-clinton-global-initiative.o.jpg/a_560x375.w1200.h630.jpg","url":"http://nymag.com/daily/intelligencer/2015/04/disastrous-clinton-post-presidency.html","plaintextTitle":"The Disastrous Clinton Post-Presidency"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/greatest-hits/instances/di@published',
    value: '{"title":"Greatest Hits","content":[{"_ref":"localhost/daily/intelligencer/components/greatest-hit/instances/0@published"},{"_ref":"localhost/daily/intelligencer/components/greatest-hit/instances/1@published"},{"_ref":"localhost/daily/intelligencer/components/greatest-hit/instances/2@published"}]}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/bedford-bowery-promo/instances/di@published',
    value: '{"subtitle":"Where downtown Manhattan and north Brooklyn intersect."}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/masthead/instances/di@published',
    value: '{"title":"Our Writers","items":[{"_ref":"localhost/daily/intelligencer/components/masthead-editor/instances/0@published"},{"_ref":"localhost/daily/intelligencer/components/masthead-editor/instances/1@published"},{"_ref":"localhost/daily/intelligencer/components/masthead-editor/instances/2@published"},{"_ref":"localhost/daily/intelligencer/components/masthead-editor/instances/3@published"},{"_ref":"localhost/daily/intelligencer/components/masthead-editor/instances/4@published"},{"_ref":"localhost/daily/intelligencer/components/masthead-editor/instances/5@published"},{"_ref":"localhost/daily/intelligencer/components/masthead-editor/instances/6@published"},{"_ref":"localhost/daily/intelligencer/components/masthead-editor/instances/7@published"}]}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/ad/instances/topLeaderboardTabletHomepage@published',
    value: '{"description":"Top leaderboard on Tablet","name":"/4088/nym.nymag/Daily_Intelligencer","label":"TabletLeaderboard","viewportMin":728,"viewportMax":1024,"sizes":"728x90"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/ad/instances/rightColMobileHomepage@published',
    value: '{"description":"Right column ad mobile 1","name":"/4088/nym.nymag/Daily_Intelligencer_Mobile","label":"colMobile","viewportMax":480,"sizes":"320x50,320x100","bordered":"yes"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/ad/instances/rightColMobileLandscapeHomepage@published',
    value: '{"description":"Right column ad mobile 1 landscape","name":"/4088/nym.nymag/Daily_Intelligencer_Mobile","label":"colMobile","viewportMin":480,"viewportMax":728,"sizes":"468x60,480x60"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/ad/instances/rightColDesktopSquareHomepage@published',
    value: '{"description":"Square ad right column desktop","name":"/4088/nym.nymag/Daily_Intelligencer","label":"RightColMidMPU","viewportMin":1024,"sizes":"300x250"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/most-popular/instances/di@published',
    value: '{"title":"Most Viewed Stories","limit":10,"articles":[{"primaryHeadline":"Louis C.K. on the Right to Be Offensive, Why White Guys Should Stop Whining, and Bored Masturbation","feedImgUrl":"http://pixel.nymag.com/imgs/daily/vulture/2016/06/09/magazine/10-louisck-cover-story-desktop.w235.h157.2x.jpg","canonicalUrl":"http://www.vulture.com/2016/06/louis-ck-horace-and-pete-c-v-r.html","plaintextPrimaryHeadline":"Louis C.K. on the Right to Be Offensive, Why White Guys Should Stop Whining, and Bored Masturbation"},{"primaryHeadline":"How Donald Trump Is Actually Winning Over the Republican Donor Class","feedImgUrl":"http://pixel.nymag.com/imgs/daily/intelligencer/2016/06/14/14-donald-trump-masks.w235.h157.2x.jpg","canonicalUrl":"http://nymag.com/daily/intelligencer/2016/06/trumps-winning-over-the-republican-donor-class.html","plaintextPrimaryHeadline":"How Donald Trump Is Actually Winning Over the Republican Donor Class"},{"primaryHeadline":"Red Hot Chili Peppers Carpool Karaoke: James Corden and Anthony Kiedis Take Their Shirts Off and Wrestle It Out — Not Necessarily in That Order","feedImgUrl":"http://pixel.nymag.com/imgs/daily/vulture/2016/06/14/14-carpool-karaoke.w235.h157.2x.JPG","canonicalUrl":"http://www.vulture.com/2016/06/rhcp-carpool-karaoke-corden-and-kiedis-wrestle.html","plaintextPrimaryHeadline":"Red Hot Chili Peppers Carpool Karaoke: James Corden and Anthony Kiedis Take Their Shirts Off and Wrestle It Out — Not Necessarily in That Order"},{"primaryHeadline":"A Black Woman Spoke at Apple’s Tech Conference and Twitter Went Wild","feedImgUrl":"http://pixel.nymag.com/imgs/fashion/daily/2016/06/13/13-bozoma-saint-john.w235.h157.2x.jpg","canonicalUrl":"http://nymag.com/thecut/2016/06/bozoma-saint-john-presented-at-wwdc.html","plaintextPrimaryHeadline":"A Black Woman Spoke at Apple’s Tech Conference and Twitter Went Wild"},{"primaryHeadline":"How Sting’s Daughter Sabotaged Her Music Career","feedImgUrl":"http://pixel.nymag.com/imgs/fashion/daily/2016/06/13/eliot-sumner/14-eliot-sumner-primary.w235.h157.2x.jpg","canonicalUrl":"http://nymag.com/thecut/2016/06/eliot-sumner-vaal-c-v-r.html","plaintextPrimaryHeadline":"How Sting’s Daughter Sabotaged Her Music Career"},{"primaryHeadline":"Who Becomes King on Game of Thrones If (When) Tommen Dies?","feedImgUrl":"http://pixel.nymag.com/imgs/daily/vulture/2016/06/13/13-tommen-got.w235.h157.2x.jpg","canonicalUrl":"http://www.vulture.com/2016/06/king-after-tommen-on-game-of-thrones.html","plaintextPrimaryHeadline":"Who Becomes King on Game of Thrones If (When) Tommen Dies?"},{"primaryHeadline":"Search Teams Find Body of 2-Year-Old Boy Attacked by Alligator at Disney World Resort, in Orlando","feedImgUrl":"http://pixel.nymag.com/imgs/daily/intelligencer/2016/06/15/14-alligator-toddler-orlando.w235.h157.2x.jpg","canonicalUrl":"http://nymag.com/daily/intelligencer/2016/06/alligator-attacks-toddler-at-disney-world-resort.html","plaintextPrimaryHeadline":"Search Teams Find Body of 2-Year-Old Boy Attacked by Alligator at Disney World Resort, in Orlando"},{"primaryHeadline":"10 Extremely Precise Words for Emotions You Didn’t Even Know You Had","feedImgUrl":"http://pixel.nymag.com/imgs/daily/science/2016/06/14/14-emotional-granularity-vocabulary.w235.h157.2x.jpg","canonicalUrl":"http://nymag.com/scienceofus/2016/06/10-extremely-precise-words-for-emotions-you-didnt-even-know-you-had.html","plaintextPrimaryHeadline":"10 Extremely Precise Words for Emotions You Didn’t Even Know You Had"},{"primaryHeadline":"Kate Beckinsale Defends Her Daughter’s Right to Google Pictures of Her Dad, Michael Sheen, Naked","feedImgUrl":"http://pixel.nymag.com/imgs/daily/vulture/2016/06/15/15-kate-beckinsale.w235.h157.2x.JPG","canonicalUrl":"http://www.vulture.com/2016/06/kate-beckinsales-daughter-dad-michael-sheen-naked-picture.html","plaintextPrimaryHeadline":"Kate Beckinsale Defends Her Daughter’s Right to Google Pictures of Her Dad, Michael Sheen, Naked"},{"primaryHeadline":"After Orlando, It’s Clearer Than Ever: This Election Is a Civil War","feedImgUrl":"https://pixel.nymag.com/imgs/fashion/daily/2016/06/14/14-trump-hillary-civil-war.w235.h157.2x.jpg","canonicalUrl":"http://nymag.com/thecut/2016/06/orlando-response-election-civil-war.html","plaintextPrimaryHeadline":"After Orlando, It’s Clearer Than Ever: This Election Is a Civil War"}]}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/newsletter-sign-up/instances/di@published',
    value: '{"title":"Get Daily Intelligencerʼs Top Stories Delivered Daily","newsletterId":2093417465,"source":"di","emailMessage":"Enter your email","signUpMessage":"Sign Up","successMessage":"Thank you for signing up!","errorMessage":"An error occurred. Please try again."}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/ad/instances/rightColMobileHomepage@published',
    value: '{"description":"Right column ad mobile 1","name":"/4088/nym.nymag/Daily_Intelligencer_Mobile","label":"colMobile","viewportMax":480,"sizes":"320x50,320x100","bordered":"yes"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/ad/instances/topLeaderboardTabletHomepage@published',
    value: '{"description":"Top leaderboard on Tablet","name":"/4088/nym.nymag/Daily_Intelligencer","label":"TabletLeaderboard","viewportMin":728,"viewportMax":1024,"sizes":"728x90"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/ad/instances/rightColMobileLandscapeHomepage@published',
    value: '{"description":"Right column ad mobile 1 landscape","name":"/4088/nym.nymag/Daily_Intelligencer_Mobile","label":"colMobile","viewportMin":480,"viewportMax":728,"sizes":"468x60,480x60"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/ad/instances/rightColDesktopHomepage@published',
    value: '{"description":"Tall right column ad desktop","name":"/4088/nym.nymag/Daily_Intelligencer","label":"RightColTopMPU","viewportMin":1024,"sizes":"300x600,300x1050"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/global-footer/instances/di@published',
    value: '{"linksEnabled":{"home":false,"magazine":false,"entertainment":false,"restaurants":false,"bars":false,"shopping":false,"travel":false,"homeDesign":false,"weddings":false,"realEstate":false,"nycTouristGuide":false,"bestOfNewYork":false,"dating":false,"deals":false,"marketplace":false,"dailyIntelligencer":false,"scienceofus":false,"theCut":false,"vulture":false,"grubStreet":false},"socialEnabled":{"newsletters":"true,","facebook":true,"twitter":true,"pinterest":false,"ios":false,"instagram":true,"rss":true,"feedly":true}}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/ad/instances/bottomLeaderboardDesktopHomepage@published',
    value: '{"description":"Bottom leaderboard desktop","name":"/4088/nym.nymag/Daily_Intelligencer","label":"BottomLeaderboard","viewportMin":1024,"sizes":"728x90,728x91,970x90,970x91,1024x90,1024x91"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/clay-kiln/instances/general@published',
    value: '{"allow":true}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/public-login/instances/no-name@published',
    value: '{"askName":false}' },
  { key: 'localhost/daily/intelligencer/components/mixpanel/instances/di-index@published',
    value: '{"layoutLabels":[{"text":"index"}]}',
    type: 'put' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/omniture/instances/di-index@published',
    value: '{"rsid":"nymcom","prop1":"Daily Intelligencer -- New York News -- New York Magazine","prop2":"Section Page","prop6":"Daily Intelligencer:All:Index","prop12":"Online"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/two-column-layout/instances/index@published',
    value: '{"head":"head","headLayout":[{"_ref":"localhost/daily/intelligencer/components/clay-meta-title/instances/index@published"},{"_ref":"localhost/daily/intelligencer/components/clay-meta-url/instances/index@published"},{"_ref":"localhost/daily/intelligencer/components/clay-meta-description/instances/index@published"},{"_ref":"localhost/daily/intelligencer/components/meta-image/instances/index@published"},{"_ref":"localhost/daily/intelligencer/components/clay-meta-site/instances/index@published"},{"_ref":"localhost/daily/intelligencer/components/clay-meta-keywords/instances/di@published"},{"_ref":"localhost/daily/intelligencer/components/meta-icons/instances/di@published"},{"_ref":"localhost/daily/intelligencer/components/head-link-newsfeed-next-prev@published"}],"top":[{"_ref":"localhost/daily/intelligencer/components/ad/instances/topLeaderboardMobileLandscapeHomepage@published"},{"_ref":"localhost/daily/intelligencer/components/ad/instances/topLeaderboardMobileHomepage@published"},{"_ref":"localhost/daily/intelligencer/components/global-nav/instances/social-off@published"}],"pageHeader":[{"_ref":"localhost/daily/intelligencer/components/di-header/instances/index@published"},{"_ref":"localhost/daily/intelligencer/components/simple-header/instances/index@published"},{"_ref":"localhost/daily/intelligencer/components/top-stories/instances/index@published"},{"_ref":"localhost/daily/intelligencer/components/early-often/instances/di@published"}],"adSplash":[{"_ref":"localhost/daily/intelligencer/components/ad/instances/topLeaderboardDesktopHomepage@published"},{"_ref":"localhost/daily/intelligencer/components/ad/instances/topLeaderboardTabletHomepage@published"},{"_ref":"localhost/daily/intelligencer/components/ad/instances/outOfPageHomepage@published"}],"main":"main","primary":[],"secondary":[],"tertiary":[{"_ref":"localhost/daily/intelligencer/components/ad/instances/rightColDesktopHomepage@published"},{"_ref":"localhost/daily/intelligencer/components/ad/instances/rightColMobileLandscapeHomepage@published"},{"_ref":"localhost/daily/intelligencer/components/ad/instances/topLeaderboardTabletHomepage@published"},{"_ref":"localhost/daily/intelligencer/components/ad/instances/rightColMobileHomepage@published"},{"_ref":"localhost/daily/intelligencer/components/newsletter-sign-up/instances/di@published"},{"_ref":"localhost/daily/intelligencer/components/most-popular/instances/di@published"},{"_ref":"localhost/daily/intelligencer/components/ad/instances/rightColDesktopSquareHomepage@published"},{"_ref":"localhost/daily/intelligencer/components/ad/instances/rightColMobileLandscapeHomepage@published"},{"_ref":"localhost/daily/intelligencer/components/ad/instances/rightColMobileHomepage@published"},{"_ref":"localhost/daily/intelligencer/components/ad/instances/topLeaderboardTabletHomepage@published"},{"_ref":"localhost/daily/intelligencer/components/masthead/instances/di@published"},{"_ref":"localhost/daily/intelligencer/components/bedford-bowery-promo/instances/di@published"},{"_ref":"localhost/daily/intelligencer/components/greatest-hits/instances/di@published"}],"bottom":[{"_ref":"localhost/daily/intelligencer/components/ad/instances/bottomLeaderboardDesktopHomepage@published"},{"_ref":"localhost/daily/intelligencer/components/global-footer/instances/di@published"}],"foot":[{"_ref":"localhost/daily/intelligencer/components/omniture/instances/di-index@published"},{"_ref":"localhost/daily/intelligencer/components/mixpanel/instances/di-index@published"},{"_ref":"localhost/daily/intelligencer/components/public-login/instances/no-name@published"},{"_ref":"localhost/daily/intelligencer/components/clay-kiln/instances/general@published"}]}' } ];

module.exports.page = [ { type: 'put',
    key: 'localhost/daily/intelligencer/components/clay-paragraph/instances/ciybrxdqj00144v8jsk0ksxyw',
    value: '{"text":""}' },
  { key: 'localhost/daily/intelligencer/components/mediaplay-image/instances/ciybrxdqj00134v8j8vx6mz44',
    value: '{"url":"","rendition":"horizontal","caption":"","credit":"","alt":"","imageLink":"","slideshowJSONPath":"","slideshowButtonText":"View Slideshow","slideshowType":"none","imageType":""}',
    type: 'put' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/share-button/instances/ciybrxdqj00124v8jyeatbet7',
    value: '{"socialNetwork":"twitter","handle":"intelligencer","buttonText":"Tweet this Story"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/share-button/instances/ciybrxdqj00114v8jz9zzdsdt',
    value: '{"socialNetwork":"facebook","handle":"NewYorkMag","buttonText":"Share on Facebook"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/ad/instances/ciybrxdqj00104v8jcid8l06e',
    value: '{"description":"In article subsequent mobile ad","name":"/4088/nym.nymag/Daily_Intelligencer_Mobile","label":"inArticle","viewportMax":600,"sizes":"320x50,320x100,300x250"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/ad/instances/ciybrxdqj000z4v8j2gl8c3hk',
    value: '{"description":"In article first mobile ad","name":"/4088/nym.nymag/Daily_Intelligencer_Mobile","label":"inArticle","viewportMax":600,"sizes":"300x250,300x252"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/ad/instances/ciybrxdqj000y4v8j4ysjbzif',
    value: '{"description":"In article tablet ad","name":"/4088/nym.nymag/Daily_Intelligencer","label":"inArticle","viewportMin":600,"viewportMax":1024,"sizes":"300x250"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/ad/instances/ciybrxdqj000x4v8jd6m618po',
    value: '{"description":"In article desktop premium ad","name":"/4088/nym.nymag/Daily_Intelligencer","label":"premiumDesktop","viewportMin":1024,"sizes":"865x310,865x654"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/ad/instances/ciybrxdqj000w4v8jcyuqwvtr',
    value: '{"description":"Out Stream desktop ad","name":"/4088/nym.nymag/Daily_Intelligencer","label":"outStreamDesktop","viewportMin":1024,"sizes":"528x379"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/bottom-share/instances/ciybrxdqj000v4v8j0uwpwtj1',
    value: '{"services":[{"_ref":"localhost/daily/intelligencer/components/share-button/instances/ciybrxdqj00114v8jz9zzdsdt"},{"_ref":"localhost/daily/intelligencer/components/share-button/instances/ciybrxdqj00124v8jyeatbet7"}]}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/clay-share/instances/ciybrxdqj000u4v8jrqbdnmf0',
    value: '{"enabled":{"facebook":true,"twitter":true,"linkedin":false,"gplus":true,"pinterest":true,"tumblr":false,"email":true,"print":true,"comment":true},"url":"","title":"","twitterHandle":"intelligencer","description":"","pinImage":"","emailPrefix":"I saw this on Daily Intelligencer and thought you might be interested...","orientation":"vertical"}' },
  { key: 'localhost/daily/intelligencer/components/tags/instances/ciybrxdqj000t4v8jhpi5wyvd',
    value: '{"items":[]}',
    type: 'put' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/article/instances/ciybrxdqj00154v8j2tquoxx6',
    value: '{"primaryHeadline":"","seoHeadline":"","shortHeadline":"","feedImgUrl":"","feedLayout":"small","teaser":"","slug":"","authors":[],"rubric":"","rubricMessage":"","syndicatedUrl":"","syndicationStatus":"original","dropCap":false,"content":[{"_ref":"localhost/daily/intelligencer/components/mediaplay-image/instances/ciybrxdqj00134v8j8vx6mz44"},{"_ref":"localhost/daily/intelligencer/components/clay-paragraph/instances/ciybrxdqj00144v8jsk0ksxyw"}],"tags":{"_ref":"localhost/daily/intelligencer/components/tags/instances/ciybrxdqj000t4v8jhpi5wyvd"},"sideShare":{"_ref":"localhost/daily/intelligencer/components/clay-share/instances/ciybrxdqj000u4v8jrqbdnmf0"},"bottomShare":{"_ref":"localhost/daily/intelligencer/components/bottom-share/instances/ciybrxdqj000v4v8j0uwpwtj1"},"feeds":{"sitemaps":true,"rss":true,"most-popular":true,"newsfeed":true},"featureTypes":{"News-Aggregation":false,"News-Commentary and Analysis":false,"News-Original Reporting":false,"Advice":false,"Cover Story Online":false,"First-Person Essay":false,"Interview or Profile":false,"List or Roundup":false,"Look Book":false,"Review":false,"Slideshow Intro":false,"TV Recap":false,"Other Feature or Column":false,"New York Magazine Story":false,"Sponsored":false},"crosspost":{"di":false,"vulture":false,"thecut":false,"scienceofus":false,"grubstreet":false,"selectall":false,"strategist":false,"vindicated":false,"betamale":false,"nyxny":false},"inArticleDesktopOutStreamAd":{"_ref":"localhost/daily/intelligencer/components/ad/instances/ciybrxdqj000w4v8jcyuqwvtr"},"inArticleDesktopPremiumAd":{"_ref":"localhost/daily/intelligencer/components/ad/instances/ciybrxdqj000x4v8jd6m618po"},"inArticleTabletAd":{"_ref":"localhost/daily/intelligencer/components/ad/instances/ciybrxdqj000y4v8j4ysjbzif"},"inArticleMobileFirstAd":{"_ref":"localhost/daily/intelligencer/components/ad/instances/ciybrxdqj000z4v8j2gl8c3hk"},"inArticleMobileSubsequentAd":{"_ref":"localhost/daily/intelligencer/components/ad/instances/ciybrxdqj00104v8jcid8l06e"},"inArticleDesktop300x250":{},"graphicBrandingRubric":"di","graphicBrandingRubricMediaPath":"public/media/sites/di/di-feature-rubric.svg"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/prev-next/instances/ciybrxdq3000m4v8jhisxtvts',
    value: '{"prev":{},"next":{}}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/clay-meta-title/instances/ciybrxdq4000n4v8jzqktzxhb',
    value: '{"title":""}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/clay-meta-url/instances/ciybrxdq5000o4v8j23iao0w5',
    value: '{"url":""}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/clay-meta-description/instances/ciybrxdq5000p4v8j7nu6i1fq',
    value: '{"description":""}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/meta-image/instances/ciybrxdq5000q4v8jv7ijaug6',
    value: '{"feedImgUrl":"","feedLayout":"","default":"//nymag.com/daily/intelligencer/media/sites/di/icon.1500x1500.png"}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/clay-meta-keywords/instances/ciybrxdq6000r4v8j4m2qi8s3',
    value: '{"tags":[]}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/components/meta-authors/instances/ciybrxdq8000s4v8j6q110b6w',
    value: '{"authors":[],"authorSocials":[]}' },
  { type: 'put',
    key: 'localhost/daily/intelligencer/pages/ciybrxdpy000l4v8j4rtunooy',
    value: '{"main":["localhost/daily/intelligencer/components/article/instances/ciybrxdqj00154v8j2tquoxx6","localhost/daily/intelligencer/components/prev-next/instances/ciybrxdq3000m4v8jhisxtvts"],"head":["localhost/daily/intelligencer/components/clay-meta-title/instances/ciybrxdq4000n4v8jzqktzxhb","localhost/daily/intelligencer/components/clay-meta-url/instances/ciybrxdq5000o4v8j23iao0w5","localhost/daily/intelligencer/components/clay-meta-description/instances/ciybrxdq5000p4v8j7nu6i1fq","localhost/daily/intelligencer/components/meta-image/instances/ciybrxdq5000q4v8jv7ijaug6","localhost/daily/intelligencer/components/clay-meta-keywords/instances/ciybrxdq6000r4v8j4m2qi8s3","localhost/daily/intelligencer/components/meta-authors/instances/ciybrxdq8000s4v8j6q110b6w"],"layout":"localhost/daily/intelligencer/components/layout/instances/article"}' } ]
